apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-0
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/ckan/default"