apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ckan-chart.fullname" . }}
  labels:
    {{- include "ckan-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ckan-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ckan-chart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "ckan-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{ if .Values.pvc.enabled }}
      volumes:
        - name: "ckan"
          persistentVolumeClaim:
            claimName: "ckan"
      {{ end }}
      {{ if .Values.pvc.enabled }}
      initContainers:
      - name: set-volume-ownership
        image: busybox
        command: ["sh", "-c", "chown -R 92:92 /var/lib/ckan"] # 92 is the uid and gid of ckan user/group
        volumeMounts:
        - name: ckan
          mountPath: {{ .Values.ckan.storagePath }}
          readOnly: false
      {{ end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: DEBUG
              value: {{ .Values.ckan.debug | quote }}
            - name: MAINTENANCE_MODE
              value: {{ .Values.ckan.maintenanceMode | quote }}
            - name: CKAN___DEBUG
              value: {{ .Values.ckan.debug | quote }}
{{- if .Values.ckan.extraEnv }}
{{ toYaml .Values.ckan.extraEnv | indent 12 }}
{{- end }}
            - name: CKAN_SYSADMIN_NAME
              value: {{ .Values.ckan.sysadminName }}
            - name: CKAN_SYSADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: sysadminPassword
            - name: CKAN_SYSADMIN_EMAIL
              value: {{ .Values.ckan.sysadminEmail }}
            - name: CKAN__SITE_TITLE
              value: {{ .Values.ckan.siteTitle }}
            - name: CKAN_SITE_ID
              value: {{ .Values.ckan.siteId }}
            - name: CKAN_SITE_URL
              value: {{ .Values.ckan.siteUrl }}
            - name: CKAN__PLUGINS
              value: {{ .Values.ckan.ckanPlugins }}
            - name: CKAN__STORAGE_PATH
              value: {{ .Values.ckan.storagePath }}
            - name: PSQL_MASTER
              value: {{ .Values.ckan.psql.masterUser }}
            - name: PSQL_PASSWD
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: psqlMasterPassword
            - name: PSQL_DB
              value: {{ .Values.ckan.psql.masterDatabase }}
            - name: CKAN_SQLALCHEMY_URL
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: ckanSqlAlchemyUrl
            - name: CKAN_DATASTORE_WRITE_URL
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: ckanDatastoreWriteUrl
            - name: CKAN_DATASTORE_READ_URL
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: ckanDatastoreReadUrl
            - name: CKAN_SOLR_URL
              value: {{ .Values.ckan.solr }}
            - name: CKAN__REDIS__URL
              value: {{ .Values.ckan.redis }}
            - name: CKANEXT__SPATIAL__SEARCH_BACKEND
              value: {{ .Values.ckan.spatialBackend }}
            - name: CKAN__LOCALES_OFFERED
              value: {{ .Values.ckan.locale.offered | quote }}
            - name: CKAN__LOCALE_DEFAULT
              value: {{ .Values.ckan.locale.default }}
            - name: CKAN__DATAPUSHER__URL
              value: {{ .Values.ckan.datapusherUrl }}
            - name: CKAN__DATAPUSHER__CALLBACK_URL_BASE
              value: {{ .Values.ckan.datapusherCallbackUrlBase }}
            - name: CKAN___SMTP__SERVER
              value: {{ .Values.ckan.smtp.server | quote }}
            - name: CKAN___SMTP__USER
              value: {{ .Values.ckan.smtp.user }}
            - name: CKAN___SMTP__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: smtpPassword
            - name: CKAN___SMTP__MAIL_FROM
              value: {{ .Values.ckan.smtp.mailFrom }}
            - name: CKAN___SMTP__TLS
              value: {{ .Values.ckan.smtp.tls }}
            - name: CKAN___SMTP__STARTTLS
              value: {{ .Values.ckan.smtp.starttls | quote }}
            - name: CKAN__ACTIVITY_STREAMS_EMAIL_NOTIFICATIONS
              value: {{ .Values.ckan.activityStreamsEmailNotifications | quote }}
            - name: CKANEXT__ISSUES__SEND_EMAIL_NOTIFICATIONS
              value: {{ .Values.ckan.issues.sendEmailNotifications | quote }}

            # docker ckan env vars
            - name: START_CKAN
              value: "1"
            - name: POSTGRES_PASSWORD
              value: ckan
            - name: CKAN_DB_NAME
              value: {{ .Values.ckan.db.ckanDbName }}
            # TEST_CKAN_DB_NAME - not setup for prod
            - name: PGDATA
              value: /var/lib/postgresql/data/ckan/
            - name: DATASTORE_READONLY_PASSWORD
              value: datastore
            # Basic
            - name: CKAN_SITE_ID
              value: {{ .Values.ckan.siteId }}  # default
            - name: DEV_CKAN_SITE_URL
              value: {{ .Values.ckan.siteUrl }}  # http://localhost:5008
            - name: CKAN_PORT
              value: "5000"
            - name: TZ
              value: UTC
            - name: CKAN_TEST_SYSADMIN_NAME
              value: ckan_admin_test
            - name: CKAN_TEST_SYSADMIN_PASSWORD
              value: test1234
            - name: CKAN_DEBUG
              value: "False"
            - name: DEV_CKAN_SQLALCHEMY_URL
              valueFrom:
                secretKeyRef:
                  name: ckancredentials
                  key: ckanSqlAlchemyUrl

            # Test database connections
            - name: TEST_CKAN_SQLALCHEMY_URL
              value: postgresql://ckan:ckan@db/ckan_test
            - name: TEST_CKAN_DATASTORE_WRITE_URL
              value: postgresql://ckan:ckan@db/datastore_test
            - name: TEST_CKAN_DATASTORE_READ_URL
              value: postgresql://datastore_ro:datastore@db/datastore_test

            # Other services connections
            - name: DEV_CKAN_SOLR_URL
              value: {{ .Values.ckan.solr }}  # http://solr:8983/solr/ckan
            - name: DEV_CKAN_REDIS_URL
              value: {{ .Values.ckan.redis }}  # redis://redis:6379/1
            - name: CKAN_DATAPUSHER_URL
              value: {{ .Values.ckan.datapusherUrl }}  # http://datapusher:8800
            - name: TEST_CKAN_SITE_URL
              value: http://test.ckan.net
            - name: TEST_CKAN_SOLR_URL
              value: {{ .Values.ckan.solr }}
            - name: TEST_CKAN_REDIS_URL
              value: {{ .Values.ckan.redis }}
            - name: TEST_CKAN_REDIS_HOSTNAME
              value: redis-headless
            - name: CKAN_REDIS_HOSTNAME
              value: redis-headless
            - name: DEV_EXTENSIONS_WHITELIST
              value: ckan,ckanext-dcat,ckanext-spatial
            - name: CKAN_S3_AWS_ACCESS_KEY_ID
              value: XXX
            - name: CKAN_S3_AWS_SECRET_ACCESS_KEY
              value: XXX
            - name: CKAN_S3_BUCKET_NAME
              value: xxx
            - name: CKAN_S3_URL_PREFIX
              value: https://xxx.com/xxx/
            - name: CKAN_S3_AWS_REGION_NAME
              value: xxx
            # Core settings
            - name: CKAN_SMTP_SERVER
              value: email-smtp.eu-west-1.amazonaws.com:587
            - name: CKAN_SMTP_STARTTLS
              value: "True"
            
            - name: CKAN_SMTP_USER
              value: XXX
            - name: CKAN_SMTP_PASSWORD
              value: XXX
            - name: CKAN_SMTP_MAIL_FROM
              value: xxx@example.uk
            # Extensions

            - name: CKAN__HARVEST__MQ__TYPE
              value: redis
            - name: CKAN__HARVEST__MQ__HOSTNAME
              value: "redis-headless" 
            - name: CKAN__HARVEST__MQ__PORT
              value: "6379"
            - name: CKAN__HARVEST__MQ__REDIS_DB
              value: "1"
            - name: CKAN__HARVEST__TIMEOUT
              value: "10"

          # readinessProbe:
          #   httpGet:
          #     path: /api/3/action/status_show
          #     port: http
          #   initialDelaySeconds: {{ .Values.ckan.readiness.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.ckan.readiness.periodSeconds }}
          #   failureThreshold: {{ .Values.ckan.readiness.failureThreshold }}
          #   timeoutSeconds: {{ .Values.ckan.readiness.timeoutSeconds }}
          # livenessProbe:
          #   httpGet:
          #     path: /api/3/action/status_show
          #     port: http
          #   initialDelaySeconds: {{ .Values.ckan.liveness.initialDelaySeconds }}
          #   periodSeconds: {{ .Values.ckan.liveness.periodSeconds }}
          #   failureThreshold: {{ .Values.ckan.liveness.failureThreshold }}
          #   timeoutSeconds: {{ .Values.ckan.liveness.timeoutSeconds }}
          {{ if .Values.pvc.enabled }}
          volumeMounts:
          - name: "ckan"
            mountPath: {{ .Values.ckan.storagePath }}
            readOnly: false
          {{ end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
